# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('', 'Escolha uma das opções'), ('SPRING', 'Spring'), ('GAS', 'gas'), ('AEG', 'AEG')], max_length=50, verbose_name='TIPO')),
                ('fabricante', models.CharField(choices=[('', 'Escolha uma das opções'), ('GG', 'G&G'), ('CR', 'Crosman')], max_length=50, verbose_name='FAB')),
            ],
        ),
    ]
